### ISSUE TITLE
HTTP request PATCH와 PUT을 구분하여 api 개선

### ISSUE THREAD

**Issue by opklnm102** [mash-up-kr/9tique-backend#5]
# HTTP Request의 PATCH와 PUT을 구분하여 api를 개선한다.

현재 개발된 api들을 [여기](https://laracasts.com/discuss/channels/general-discussion/whats-the-differences-between-put-and-patch?page=1)를 참고 put과 patch의 차이를 인지하고 api 개선

* PUT은 해당 자원이 통채로 교체되는 것을 의미하며 PATCH는 해당 자원의 일부분만 변경되는 것을 의미
* 둘의 차이를 두는 것을 권장

**Comment by ppth0608** [comment]
크~~ 갓 동희 진짜 열심히 하네~!

**Comment by opklnm102** [comment]
#50 에서 상품 상태변경 API end point 분리 완료
